4. 예외 

4.1 사라진 SQLException

4.1.1 초난감 예외처리
- 예외블랙홀
:  catch선언 후 아무것도 안함...
* 예외를 처리할 때 반드시 지켜야 하는 핵심 원칙 한가지 - 모든 예외는 적절하게 복구되든지 아니면 작업을 중단시키고 운영자 또는 개발자에게 분명하게 통보돼야 한다.
예외를 잡아서 뭔가 조치를 취하지 않을 거라면 예외처리를 던져 책임을 전가하는 것도 괜찮다.
하지만 무작정 계속 던지는 것도 옳은 방법은 아니다.

4.1.2 예외의 종류와 특징

- Error
OutOfMemoryErro,ThreadDeath와 같은 JVM 에서 발생시키는 에러. 에플리케이션에서는 잡아서 대응 방법이 딱히 없다.

- Exception 
-- checked exception
: Excpetion 클래스의 서브클래스이면서 RuntionException 클래스를 상속하지 않은 것
-- unchecked exception
: RuntimeException을 상속한 클래스
: 주로 프로그램의 오류가 있을 때 발생하도록 의도된 것들.
: 대표적인것으로  NullPointerException, IllegalAregumentException 등 

4.1.3. 예외처리방법
- 예외복구
-- 예외상황을 파악하고 문제를 해결해서 정상상태로 돌려 놓는 것
- 예외처리 회피
-- 예외처리를 자신이 담당하지 않고 자신을 호출한 쪽으로 던지는 것
- 예외전환
-- 의미를 분명하게 해서 보내주기 SQLException에서 DuplicateUserIdException과 같은 예외로

4.1.4 예외처리 전략

4.1.5 SQLException은 어떻게 됐니?
- SQLException은 99% 어플리케이션에서 복구할 방법이 없다......그래서 사라졌다.. DataAccessException런 예외로 던져주고있다.

4.2 예외 전환



===============================================================코드===========================
```java
	/** 리스트 4-7 */
	public void add() throws SQLException {
		// JDBC API
	}
	/** 리스트 4-8 */
	public void add2() throws SQLException {
		try {
			// JDBC API
		} catch(SQLException e) {
			//로그 출럭
			throw e;
		}
	}
	/** 리스트 4-10 */
	public void add3(User user) throws DuplicateUserIdException, SQLException {
		try {
			//JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
			// 그런 기능을 가진 다른 SQLException을 던지는 메소드를 호출하는 코드
			
			//중첩예외
			/** 리스트 4-10/11 */
			try {
				
			} catch(Exception e) {
				throw DuplicateUserIdException(e);				// 중첩예외 1
				throw DuplicateUserIdException().initCause(e);	// 중첩예외 2
			}
		} catch(SQLException e) {
			//ErrorCode가 MYSQL의 "Duplicate Entry(1062)"이면 예외전환
			if(e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
				throw DuplicateUserIdExcpetion();
			else
				throw e;	//그 외의 경우는 SQLException 그대로
			
				
		}
	}
	
	/** 리스트 4-14 */
	public void add4() throws DuplicateUserIdException {
		try {
			//JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
			// 그런 기능을 가진 다른 SQLException을 던지는 메소드를 호출하는 코드
			
		} catch(SQLException e) {
			//ErrorCode가 MYSQL의 "Duplicate Entry(1062)"이면 예외전환
			//if(e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
			if(e.getErrorCode() == 333)
				throw new DuplicateUserIdException(e);
			else
				throw new RuntimeException(e);	//그 외의 경우는 SQLException 그대로
		}
	}
	
	/** 리스트 4-15 */
	public void add5() {
		try {
			BigDecimal balance = account.withdraw(amount);
			// 정상적으로 처리결과를 출력하도록 진행
		} catch (InsufficientBalanceException e) {
			// InsufficientBalanceException에 담긴 인출 가능한 간고금액 정보를 가져옴
			BigDecimal availFunds = e.getAvailFunds();
			//잔고 부족 안내 메시지를 준비하고 이를 출력하도록 진행

		}
		
	}
  
  /**  리스트 4-13 */
public class DuplicateUserIdException extends RuntimeException {
	public DuplicateUserIdException(Throwable cause) {
		super(cause);
	}
}
```
